### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RonanHiggins**

### CODE REVIEW

**Comment by nolta** [comment]
Excel!?

**Comment by RonanHiggins** [comment]
I'd be interested to see how it compresses compared to the others.. it's the most universal format in fairness and has support in most languages..

**Comment by nolta** [comment]
I'd argue CSV is the most universal, and XLSX is far more verbose than CSV ([here's an example](https://www.example-code.com/csharp/parse_xls.asp)).

**Comment by RonanHiggins** [comment]
this xlsx library is more usable.. 
https://github.com/troldal/OpenXLSX

**Comment by nolta** [comment]
For example, an ACU UDP stream file with ~30k rows, the `.csv.gz` version is 376 kiB, while the `xlsx` version is 873 kiB.

**Comment by RonanHiggins** [comment]
can you zip that XLSX?

**Comment by nolta** [comment]
It already is -- XLSX is zip'd XML.

**Comment by RonanHiggins** [comment]
that's what i thought.. how is it so much bigger?

**Comment by RonanHiggins** [comment]
okay XLSX off the table then

**Comment by nolta** [comment]
Every single value is wrapped in `<Cell><Data>...</Data></Cell>`.

**Comment by RonanHiggins** [comment]
how else will you know if that number is cell data though?

**Pull request closed without merging**
